name: Test, Build and Release apk
'on':
  push:
    branches:
      - testworkflow
  pull_request:
    branches:
      - testworkflow
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: set NOW
      id: release
      run: |
        echo "::set-output name=NOW::v$(date +'%Y%m%d.%H%M%S')"
  build:
    name: Build APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.5'
      - run: flutter pub get -v
      - run: flutter build apk --debug --split-per-abi
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: ${{ steps.release.outputs.NOW }}
          token: ${{ secrets.SECRECTS }}